# Generated by Django 3.2.3 on 2021-06-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('rating', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Comments',
            field=models.ManyToManyField(to='rating.Comment'),
        ),
        migrations.AddField(
            model_name='event',
            name='iov',
            field=models.ManyToManyField(to='rating.ImageOrVideo'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbs',
            field=models.ManyToManyField(to='rating.Thumb'),
        ),
    ]
