# Generated by Django 3.2.3 on 2021-06-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_initial'),
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date',)},
        ),
        migrations.RemoveField(
            model_name='event',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='thumbs',
        ),
        migrations.CreateModel(
            name='EventThumb',
            fields=[
                ('thumb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.thumb')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            bases=('rating.thumb',),
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.comment')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            bases=('rating.comment',),
        ),
    ]
