# Generated by Django 3.2.3 on 2021-06-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210619_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
    ]
