# Generated by Django 3.2.3 on 2021-06-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageorvideo',
            name='is_primary',
        ),
    ]
