# Generated by Django 3.2.3 on 2021-06-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20210618_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='thumbs',
        ),
        migrations.CreateModel(
            name='CommentThumb',
            fields=[
                ('thumb_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.thumb')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.comment')),
            ],
            bases=('rating.thumb',),
        ),
    ]
